version: "3.6"
services:
  icloud-api:
    image: shogoki/icloud-api
    build: . 
    environment:
      PORT: 80
    networks:
      default:
      web:

networks:
    web:
       external:
           name: webproxy
